sonar.projectKey=DevCine-F_DevCine
sonar.organization=devcine-f
sonar.modules=backend,frontend
backend.sonar.projectName=DevCine Backend
backend.sonar.projectBaseDir=devcine-backend
backend.sonar.sources=src/main/java
backend.sonar.java.binaries=target/classes
frontend.sonar.projectName=DevCine Frontend
frontend.sonar.projectBaseDir=devcine-frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/node_modules/**,**/dist/**,**/.vscode/**